### ISSUE TITLE
screen for contaminants fails

### ISSUE THREAD

**Issue by stevebaeyen** [ctmrbio/BACTpipe#114] opened 2020-09-11 12:24 UTC
I installed BACTpipe on a VM with Ubuntu 20.04 and used a genome that was previously assessed with CheckM for contaminants but the 'screen contaminants' step fails with this warning: WARN: Directive 'validExitStatus' has been deprecated -- Check process 'screen_for_contaminants'. Pipeline ended prematurely bur report was generated.

**Comment by boulund** [comment] 2020-09-15 06:46
Thanks for reporting the issue!

We are aware that BACTpipe is now rather old and not using current Nextflow best practices. Planning is currently ongoing for how to modernize and make BACTpipe more user-friendly and flexible.

**Comment by boulund** [comment] 2020-12-03 09:44
BACTpipe is getting some improvements now, and this issue should be resolved with those fixes. Please reopen this issue if it still remains in the next version.

**Closed by boulund** 2020-12-03 09:44 UTC
Labels: bug

**Comment by stevebaeyen** [comment] 2020-12-03 09:47
Thanks, will check it out !

**Comment by boulund** [comment] 2020-12-03 10:31
Sorry for being so quick to close the issue without saying when the next release is due. The next release should be out sometime soon, I hope the issue is no longer present in the next release.
